import React from 'react';
import { Icon } from '../icons/Icon.jsx';

/**
 * QRShare — a share button + QR popup for handing off a link across devices.
 *
 * A compact icon button (or labelled button) that opens a centered popup with
 * the shareable URL, a scannable QR code, and a Copy Link action. The QR image
 * is generated by the qrserver.com endpoint by default (override with `qrSrc`
 * to plug in your own generator / offline canvas).
 *
 * Self-contained: manages open + copied state internally. Closes on scrim
 * click or Escape. `url` defaults to the current location.
 */
export function QRShare({
  url,
  title = 'Share This Link',
  buttonLabel = null,        // null → icon-only button
  qrSize = 200,
  qrSrc,                     // override the QR image URL
  onOpen,
  style,
}) {
  const [open, setOpen] = React.useState(false);
  const [copied, setCopied] = React.useState(false);
  const shareUrl = url || (typeof window !== 'undefined' ? window.location.href : '');
  const qr = qrSrc || ('https://api.qrserver.com/v1/create-qr-code/?size=' + qrSize + 'x' + qrSize + '&margin=10&data=' + encodeURIComponent(shareUrl));

  React.useEffect(() => {
    if (!open) return;
    const onKey = (e) => { if (e.key === 'Escape') setOpen(false); };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [open]);

  const doOpen = () => { setCopied(false); setOpen(true); onOpen && onOpen(); };
  const copy = () => {
    if (navigator.clipboard) navigator.clipboard.writeText(shareUrl).then(() => { setCopied(true); setTimeout(() => setCopied(false), 1800); });
  };

  return (
    <>
      <button type="button" onClick={doOpen} title="Share this link" aria-label="Share"
        style={{
          display: 'inline-flex', alignItems: 'center', gap: 7, background: 'none',
          border: buttonLabel ? '1.5px solid var(--border)' : 'none',
          borderRadius: 'var(--r-sm)', padding: buttonLabel ? '7px 12px' : 6,
          color: 'var(--text-muted)', cursor: 'pointer', fontFamily: 'var(--font-ui)',
          fontSize: 13, fontWeight: 700, transition: 'color var(--dur-fast)',
          ...style,
        }}
        onMouseEnter={(e) => { e.currentTarget.style.color = 'var(--accent)'; }}
        onMouseLeave={(e) => { e.currentTarget.style.color = 'var(--text-muted)'; }}>
        <Icon name="share" size={18} color="currentColor" />
        {buttonLabel}
      </button>

      {open && (
        <div role="dialog" aria-modal="true" aria-label={title}
          style={{ position: 'fixed', inset: 0, zIndex: 300, display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: 'var(--font-ui)' }}>
          <div onClick={() => setOpen(false)} style={{ position: 'absolute', inset: 0, background: 'var(--scrim)', cursor: 'pointer' }} />
          <div style={{
            position: 'relative', background: 'var(--surface)', borderRadius: 'var(--r-lg)',
            padding: '24px 28px', maxWidth: 340, width: '90%', textAlign: 'center',
            boxShadow: 'var(--shadow-pop)', border: '1.5px solid var(--border)',
          }}>
            <h2 style={{ margin: '0 0 14px', fontSize: 16, fontWeight: 800, color: 'var(--text)', textTransform: 'uppercase', letterSpacing: '0.06em' }}>{title}</h2>
            <div style={{
              background: 'var(--surface-2)', border: '1.5px solid var(--border)', borderRadius: 'var(--r-sm)',
              padding: '8px 10px', fontSize: 12, color: 'var(--text-muted)', wordBreak: 'break-all',
              marginBottom: 16, userSelect: 'all',
            }}>{shareUrl}</div>
            <img src={qr} width={qrSize} height={qrSize} alt="QR code for the shareable link"
              style={{ display: 'block', margin: '0 auto 16px', borderRadius: 8, background: '#fff' }} />
            <div style={{ display: 'flex', gap: 8, justifyContent: 'center' }}>
              <button type="button" onClick={copy} style={{
                background: copied ? 'var(--status-success)' : 'var(--accent)', color: 'var(--on-accent)', border: 'none',
                borderRadius: 'var(--r-sm)', padding: '8px 20px', fontSize: 14, fontWeight: 700,
                cursor: 'pointer', fontFamily: 'inherit', transition: 'background var(--dur-fast)',
              }}>{copied ? 'Copied!' : 'Copy Link'}</button>
              <button type="button" onClick={() => setOpen(false)} style={{
                background: 'none', border: '1.5px solid var(--border)', borderRadius: 'var(--r-sm)',
                padding: '8px 16px', fontSize: 14, cursor: 'pointer', fontFamily: 'inherit', color: 'var(--text-muted)',
              }}>Close</button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
